### ISSUE TITLE
Crest Plugin that Scans via XBean at build time

### ISSUE THREAD

**Issue by dblevins** [tomitribe/crest#31]
crest-xstatic-plugin

If commands are turned into an uber-jar, the xbean scanning becomes very very slow.

We could scan for the classes containing @Command then put them in a file in the target/classes/ directory, then write a Commands.Loader implementation that can grab that file.

**Comment by danielsoro** [comment]
I already have a implementation for it.
I'm working in test now. :)

**Comment by dblevins** [comment]
Looks good.  Merge it in!  Just gave you write access :)

We'll probably want to change the name of the file that contains the command classes.  How about

`META-INF/annotated/org.tomitribe.crest.api.Command`

Then we'll need a new Maven module like `tomitribe-crest-xbean` that has an implementation of `Commands.Loader`.  This implementation will `getResources` for the META-INF files and pull the class names out and return them.

This new module wouldn't have a name as people could create this file by hand.  Maybe we call it  something like `tomitribe-crest-xfiles` :)

**Comment by dblevins** [comment]
We'd probably also want to update the archetype so that the usage of the shade plugin combined the `META-INF/annotated/org.tomitribe.crest.api.Command` files.

Then you could safely create an uber jar that combined many other jars containing commands.

**Comment by rmannibucau** [comment]
we have crest-commands.txt which matches it

if we want to support all annotations - including @Editors - please open another issue
