### ISSUE TITLE
support parameter injection

### ISSUE THREAD

**Issue by rmannibucau** [tomitribe/crest#37]
Would be nice to be able to delegate some parameter injections (ie the unknown ones without @Options) to a provider. Would allow service injection for instance

**Comment by dblevins** [comment]
Good feature!  Wanted this one for a while.

Doesn't appear to be any tests for @Err @Out and @In, can you add some?  If you can also add tests for the help to show @CrestAnnotation works that'd be awesome.

**Comment by dblevins** [comment]
Excellent to see the `throw new IllegalArgumentException("@In only supports InputStream injection");` validation logic in there.  Can you move that and similar into the `validate()` method?

**Comment by rmannibucau** [comment]
Test is https://github.com/tomitribe/crest/blob/849c4182e89ad8b38ca9d3437e6536315f5bd839/tomitribe-crest/src/test/java/org/tomitribe/crest/StreamInjection.java (should get renamed StreamInjectionTest).

@CrestAnnotation is just a marker, only used to hide some internal parameter (previous test shows it)

about validate() I said it in another jira but it should get reworked to get a correct runtime tree cause ATM we only rely on reflection everywhere (= no need to make things a bit better they need to be totally reworked pretty soon anyway)

**Comment by rmannibucau** [comment]
closing since released several times now
