### ISSUE TITLE
Eliminate IllegalArgumentException "No interceptor for " issue with @CrestInterceptor

### ISSUE THREAD

**Issue by dblevins** [tomitribe/crest#95]
Previously a declaration such as this would fail unless the `RedInterceptor` class was explicitly added to the list of command classes elsewhere.

        @Command(interceptedBy = RedInterceptor.class)
        public String red() {
            return "red";
        }

This change removes that issue.  The interceptor will be constructed as needed with no need to declare it anywhere other than in `@Command(interceptedBy`

**Comment by dblevins** [comment]
Fixed

**Comment by rmannibucau** [comment]
AFAIK it has a difference which is the singleton vs "dependent"/"protype" scope, so can be worth caching in the list of beans using a concurrentmap maybe - since there is no default IoC a singleton can handle dependent scope in its impl more easily than the opposite?
